Repository aravindvnair99/Spot-the-Hole, pull requests merged in 2021-05, with the labels that each got.

#80 CodeQL
  .github/workflows/codeql-analysis.yml
Labels: size/XS

#84 Homepage update and location search bar
  functions/package-lock.json
  functions/package.json
  functions/views/components/headerMenu.ejs
  functions/views/index.ejs
  functions/views/locations.ejs
  functions/views/showGlobalCodes.ejs
  public/css/style.css
Labels: CSS, EJS, dependencies

#87 Group by location instead of plus codes
  functions/index.js
  functions/package-lock.json
Labels: JS, dependencies, size/M
